# Generated by Django 5.2.3 on 2025-06-28 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrequest',
            old_name='fee_deducted',
            new_name='fee_applied',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='agent_payment_receipt',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='amount_dinar',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='deposit_amount_dinar',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='depositor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='depositor_phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='net_amount_dinar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='nita_office',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver_name',
            field=models.CharField(default='Emjaay', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
