# Generated by Django 5.2.3 on 2025-07-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrequest_agent_receipt_paymentrequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
