# Generated by Django 5.2.3 on 2025-06-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_country',
            field=models.CharField(blank=True, choices=[('nigeria', 'Nigeria'), ('niger', 'Niger'), ('cameroon', 'Cameroon')], max_length=20, null=True),
        ),
    ]
