# Generated by Django 5.2.3 on 2025-07-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
