# Generated by Django 5.2.3 on 2025-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('nigeria', 'Nigeria'), ('niger', 'Niger'), ('cameroon', 'Cameroon')], max_length=20)),
                ('market_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remar_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
