# Generated by Django 5.2.3 on 2025-07-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='currency_code',
            field=models.CharField(default='X', max_length=10),
            preserve_default=False,
        ),
    ]
