# RemarPay Backend Documentation Suite

Welcome to the backend documentation for **RemarPay**, a secure and efficient multi-role currency exchange and transaction platform. Below is a complete set of documents to support developers, maintainers, and future feature planning.

---

## 📘 `README.md`

### Project Name

**RemarPay Backend**

### Description

Django-based backend for RemarPay, supporting multi-role users (cashiers, agents, managers, tech-admins), transaction flows, rate management, user preferences, and more.

### Tech Stack

- Python 3.11+
- Django 4+
- Django REST Framework
- SimpleJWT for Authentication

### Key Features

- JWT Authentication
- Role-based permissions
- Currency exchange transaction logic
- Auto-calculated conversions + fee deduction
- Receipt generation (for frontend rendering)
- Agent payment confirmations
- User management + suspension
- Rate control and versioning
- Dark mode and timezone preferences
- Notification system
- Search & Filter system

### Setup Instructions

```bash
# Create and activate virtualenv
python -m venv venv
source venv/bin/activate  # or venv\Scripts\activate on Windows

# Install dependencies
pip install -r requirements.txt

# Migrate DB
python manage.py migrate

# Create superuser
python manage.py createsuperuser

# Run dev server
python manage.py runserver
```

---

## 🧭 `DEVELOPER_GUIDE.md`

### User Roles Summary

| Role       | Description                |
| ---------- | -------------------------- |
| Cashier    | Initiates client deposits  |
| Agent      | Confirms foreign payments  |
| Manager    | Oversees agents & cashiers |
| Tech Admin | Full system control        |

### Code Structure

- `accounts/`: User authentication, registration, profiles
- `payments/`: Cashier deposit → Agent confirmation flow
- `rates/`: Manages country-specific exchange rates
- `notifications/`: Role-based & direct notifications

### Important Commands

```bash
# Reset password
python manage.py changepassword <email>

# Load default data (optional)
python manage.py loaddata initial_data.json
```

### Key Endpoints

| Endpoint                                  | Description                       |
| ----------------------------------------- | --------------------------------- |
| POST `/api/accounts/login/`               | JWT Login                         |
| POST `/api/accounts/register/`            | Create new user (tech-admin only) |
| PATCH `/api/accounts/<id>/assign-role/`   | Assign user roles                 |
| POST `/api/payments/create/`              | Cashier payment request           |
| GET `/api/payments/agent/requests/`       | Agent’s assigned country requests |
| PATCH `/api/payments/agent/confirm/<id>/` | Agent marks as paid               |

---

## 👤 `USER_GUIDE.md`

### Cashier Flow

1. Login and access dashboard
2. Go to "New Deposit"
3. Enter client + receiver details
4. Submit → Request is created
5. Download receipt (auto-generated by frontend)

### Agent Flow

1. Login → See assigned country’s requests
2. Open unpaid requests
3. Mark as paid + upload receipt image

### Manager & Tech-Admin

- Suspend/unsuspend users
- Assign roles/countries
- View full user list
- Set or update currency exchange rates
- Send announcements (via notifications)

---

## 🔮 `FUTURE_UPDATES.md`

### Suggested Features

- Frontend PWA implementation ✅ (in progress)
- Profile pictures for users
- Admin dashboard analytics (charts)
- Export reports to CSV
- Scheduled notifications/reminders
- Email verification (optional)
- Advanced audit logging (activity logs)
- Two-factor authentication (2FA)

### Technical Improvements

- Improve permission logic with DRY rules
- Add pagination to list endpoints
- Optimize search with indexes
- Rate limiting for sensitive endpoints
- Docker support for full deployment

---

## 📦 Suggested File Tree

```
remarpay/
├── accounts/
├── payments/
├── rates/
├── notifications/
├── media/  # Profile pics & agent receipts
├── static/
├── manage.py
├── requirements.txt
├── README.md
├── DEVELOPER_GUIDE.md
├── USER_GUIDE.md
└── FUTURE_UPDATES.md
```

---

✅ **Ready for frontend development.** Let’s now start building the React + Tailwind + PWA frontend step-by-step!
